#!/usr/bin/env python3
"""pair_corrections for lzh-translation from the full read of the Chinese-Tibetan pair
(0-INBOX/temp/pair-review/zh-bo.md, 2026-10-04).

Pair: dorjeechoepa-root-zh(bo-zh).md (Kumārajīva, 430 rows) <-> dorjeechoepa-root-bo(display).md
(the Tibetan display doc = the Dzongsar 'Tsadel', 430 rows). Row N of the Chinese is paired with row N
of the Tibetan. Only clearly wrong pairings are corrected (D12): one misplaced row, two one-row slips and
two off-by-one runs. Spills, condensations, Kumārajīva-only clauses and the team's reorderings are kept
as made and listed in zh-bo.md for the text expert.
Run from the vault root:  python3 0-INBOX/temp/make_zh_bo_corrections.py
"""
import pathlib
import sys
import yaml

sys.path.insert(0, "4-SYSTEM/Skills/aligned-corpus-intake/scripts")
from md_export import read_rows            # noqa: E402
from project import is_letter              # noqa: E402

has = lambda t: any(is_letter(c) for c in t)
zh = {r["row"]: r["text"] for r in read_rows("0-INBOX/raw-data/dorjeechoepa-root-zh(bo-zh).md")}
bo = {r["row"]: r["text"] for r in read_rows("0-INBOX/raw-data/dorjeechoepa-root-bo(display).md")}
CL = ('Claude (standing instruction "read it and fix if it really makes sense", carried over from '
      'heart-sutra-rails 2026-10-03; D12) — for the text expert to check')
DATE = "2026-10-04"
out = []


def fix(row, targets, reason):
    assert has(zh.get(row, "")), f"Chinese row {row} is empty"
    for t in targets:
        assert has(bo.get(t, "")), f"Tibetan row {t} is empty"
    out.append({"row": row, "target_side_rows": targets, "reason": reason, "decided_by": CL, "date": DATE})


fix(19, [27], "Subhūti's assent 「唯然。世尊！願樂欲聞。」 renders Tibetan row 27 (བཅོམ་ལྡན་འདས་དེ་དེ་བཞིན་ནོ། །ཞེས་གསོལ་ནས།), "
    "whose Chinese row is empty; it was placed opposite row 19 (དེ་སྐད་ཅེས་གསོལ་པ་དང༌།, the tag closing Subhūti's "
    "question), which Kumārajīva has no words for. In both texts the assent follows the Buddha's 「…如是降伏其心。」 (row 26). "
    "The Chinese row stays where the doc has it.")
fix(243, [244], "One-row slip: 是人先世罪業應墮惡道，以今世人輕賤故 renders the first half of Tibetan row 244 "
    "(ཚེ་རབས་སྔ་མའི་མི་དགེ་བའི་ལས་ངན་སོང་དུ་སྐྱེ་བར་འགྱུར་བ… ཚེ་འདི་ཉིད་ལ་མནར་བས།), not row 243 (ཤིན་ཏུ་མནར་བར་འགྱུར་རོ།), "
    "which Kumārajīva renders together with row 242 (若為人輕賤). Row 244 (先世罪業則為消滅) keeps its pairing.")
# off-by-one run 298-301: Subhūti's answer about the divine eye is split over Chinese 297-298
run = {298: [297], 299: [298], 300: [299], 301: [300, 301]}
for r, t in run.items():
    fix(r, t, "Off-by-one run, Chinese rows 298-301: Kumārajīva's answer 「如是，世尊！ / 如來有天眼。」 takes two rows "
        "(297-298) where the Tibetan has one (297: …དེ་བཞིན་གཤེགས་པ་ལ་ལྷའི་སྤྱན་མངའོ།), so each following Chinese row "
        f"renders the Tibetan row before it. Chinese row {r} renders Tibetan row(s) {', '.join(map(str, t))}"
        + ("; row 301 (「如是，世尊！如來有慧眼。」) renders 300 + 301 and the pairing is back in step." if r == 301 else "."))
# off-by-one run 325-336: Kumārajīva has nothing for Tibetan 324-325; the Chinese slips one row
run = {325: [326], 327: [326], 328: [327], 329: [328], 330: [329], 331: [330], 332: [331], 333: [332],
       334: [333], 335: [334], 336: [335, 336]}
for r, t in run.items():
    why = {325: "row 325 (「須菩提！) is the vocative of the sentence in row 327, which renders Tibetan 326 "
                "(ཡང་རབ་འབྱོར་གལ་ཏེ་བསོད་ནམས་ཀྱི་ཕུང་པོ…); Tibetan 325 (…བསོད་ནམས་ཀྱི་ཕུང་པོ་མང་དུ་བསྐྱེད་དོ།) has no Chinese",
           336: "row 336 (「不也，世尊！如來不應以具足諸相見。) renders Tibetan 335 + 336 and the pairing is back in step"}.get(r)
    fix(r, t, "Off-by-one run, Chinese rows 325-336 (Kumārajīva has nothing for Tibetan 324-325, and the empty "
        f"Chinese row stands at 326 instead of 325): Chinese row {r} renders Tibetan row(s) {', '.join(map(str, t))}"
        + (f"; {why}." if why else "."))
fix(382, [381], "One-row slip in the verse: 是人行邪道 renders the third line of Tibetan row 381 (ལོག་པའི་ལམ་དུ་ཞུགས་པ་སྟེ།), "
    "not row 382.")
fix(383, [382], "One-row slip in the verse: 不能見如來 renders Tibetan row 382 (སྐྱེ་བོ་དེ་དག་ང་མི་མཐོང༌།), not row 383 "
    "(སངས་རྒྱས་རྣམས་ནི་ཆོས་ཉིད་ལྟ།, the second stanza, which Kumārajīva does not have).")

pathlib.Path("0-INBOX/temp/pair-review/zh-bo-corrections.yaml").write_text(
    "# pair_corrections for lzh-translation (row = row of dorjeechoepa-root-zh(bo-zh).md; target_side_rows = rows of\n"
    "# dorjeechoepa-root-bo(display).md). Evidence: zh-bo.md (full read, 2026-10-04). GENERATED by make_zh_bo_corrections.py.\n"
    + yaml.safe_dump({"pair_corrections": out}, allow_unicode=True, sort_keys=False, width=200), encoding="utf-8")
print(len(out), "corrections")
